section view

diff --git a/ci/run-vint b/ci/run-vint
--- a/ci/run-vint
+++ b/ci/run-vint
@@ -8,4 +8,11 @@ exit_code=0
 
 docker_flags=(--rm -v "$PWD:/testplugin" -v "$PWD/test:/home" -w /testplugin "$image")
 
-echo '------------------
+echo '----------------------------------------'
+echo 'Running Vint...'
+echo '----------------------------------------'
+echo 'Vint warnings/errors follow:'
+echo
+
+set -o pipefail
+docker run -a stdout "${docker_flags[@]}" vint -w . || exit_c
